<?php

/* DO NOT EDIT THIS FILE! */

/* Configuration */

//Configs
require_once 'config/config.php';
require_once 'config/remove-comments.php';
require_once 'config/register-menu.php';
require_once 'config/acf_seo.php';

//CPT
add_action('init', function () {
	require_once 'config/custom_post_types.php';
});

//Endpoints
add_action('rest_api_init', function () {

	//Built in fields and endpoints
	require_once dirname(__FILE__) . '/inc/endpoints/settings.php';
	require_once dirname(__FILE__) . '/inc/fields.php';

	//Add fields and custom to previews
	add_filter('rest_prepare_revision', function ($response, $post) {
		$data = $response->get_data();

		$data['meta_seo'] = (object) [
			'title' => get_the_title($post->ID),
			'description' => str_replace('[&hellip;]', '' , get_the_excerpt($post->ID))
		];
		$data['fields'] = get_fields($post->ID);
		$data['custom'] = (object) [];

		$template = get_page_template($post->ID);
		$type     = get_post_type($post->ID);

		if ($template) {
			$data['custom'] = apply_filters('api_custom_template_' . str_replace('.php', '', $template), (object) [], $post->ID);
		} else if ($type) {
			$data['custom'] = apply_filters('api_custom_type_' . $type, (object) [], $post->ID);
		}

		return rest_ensure_response($data);
	}, 10, 2);

	//Include custom api endpoints and fields
	require_once dirname(__FILE__) . '/api/filters.php';
	if (LBB_ENABLE_DYNAMIC_IMPORT) {
		foreach (glob(dirname(__FILE__) ."/api/endpoints/*.php") as $endpoint) {
			require_once $endpoint;
		}
		foreach (glob(dirname(__FILE__) ."/api/custom/*.php") as $custom) {
			require_once $custom;
		}

		foreach (glob(dirname(__FILE__) ."/api/fields/*.php") as $field) {
			require_once $field;
		}
	} else {
		require_once dirname(__FILE__) . '/api/endpoints/endpoints.php';
		require_once dirname(__FILE__) . '/api/custom/custom_section.php';
		require_once dirname(__FILE__) . '/api/custom/custom_template.php';
		require_once dirname(__FILE__) . '/api/custom/custom_type.php';
		require_once dirname(__FILE__) . '/api/fields/fields.php';
	}

});

function lbb_preview_post_link($link) {
	global $post;
	return $link.'&type='.$post->post_type.'&id='.$post->ID;
}
add_filter('preview_post_link', 'lbb_preview_post_link');

//Helpers
function lbb_getAllPostTypes() {
	return array_merge(['page','post'], array_values(get_post_types(['public' => true, '_builtin' => false])));
}

add_filter('acf/load_value/name=sections', 'add_default_sections', 10, 3);
function add_default_sections($value, $post_id, $field)
{

	//Only on new posts
	if ($value !== null) {
		return $value;
	}

	$default_sections = [
		/*
		[
			'acf_fc_layout' => 'section_name_here'
		],*/
	];

	return $default_sections;
}


//Custom
require_once 'config/custom-functions.php';